version: '3.5'

services:
  db:
    image: nouchka/sqlite3

  web:
    build: .
    command: gunicorn chef.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/beatrizoliveira/Documentos/chefemcasa
      - static_volume:/home/beatrizoliveira/Documentos/chefemcasa/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/beatrizoliveira/Documentos/chefemcasa/staticfiles
    ports:
      - 1337:80 
    depends_on:
      - web
volumes:
  static_volume:
