# Generated by Django 2.1.4 on 2019-03-11 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chef_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chef',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='chef',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
